language: minimal
script:
  - docker-compose -f docker-compose.test.yml -p avrae build
  - docker-compose -f docker-compose.test.yml -p avrae up -d
  - docker logs -f avrae_tests_1
  - docker wait avrae_tests_1
  - docker build -t avrae-bot .
after_success:
  - cp shared/.coverage .coverage
  - pip install coverage
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
deploy:
  provider: script
  script: bash scripts/ecr_push.sh
  on:
    branch: master
